k-최근접 이웃(KNN) 분류기는 기술적으로 예측을 만들기 위해 모델을 훈련하지 않음. 대신 가장 가까운 k개의 샘플에서 다수으 ㅣ클래스를 그 샘플의 클래스로 예측. 예로, 클래스가 알려지지 않은 한 샘플이 클래스 1인 샘플로 둘러싸여 있다면 그 샘플을 클래스 1로 분류.

# 15.1 샘플의 최근접 이웃 찾기

샘플에서 가장 가까운 k개의 샘플(이웃)을 찾음. - 사이킷런의 NearestNeighbors 사용.

In [4]:
from sklearn import datasets
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()

X = iris.data

standardizer =StandardScaler()

X_standardized = standardizer.fit_transform(X)


# k=2인 최근접 이웃 모델을 만듬.
nearest_neighbors = NearestNeighbors(n_neighbors=2).fit(X_standardized)

# 새로운 샘플 생성
new_observation = [1,1,1,1]

# 이 샘플과 가장 가까운 이웃으 ㅣ인덱스와 거리를 찾음.
distances, indices = nearest_neighbors.kneighbors([new_observation])

# 최근접 이웃을 확인.
X_standardized[indices]

array([[[1.03800476, 0.55861082, 1.10378283, 1.18556721],
        [0.79566902, 0.32841405, 0.76275827, 1.05393502]]])

In [8]:
X_standardized[indices]

array([[[1.03800476, 0.55861082, 1.10378283, 1.18556721],
        [0.79566902, 0.32841405, 0.76275827, 1.05393502]]])

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

해결에서 붓꽃 데이터셋을 사용. 임의의 값으로 새로운 샘플 new_observation를 만들고 데이터셋에서 가장 가까운 두 개의 샘플을 찾음. indices에는 데이터셋에서 가장 가까운 샘플의 위치가 담김. 찾은 샘플의 값을 보려면 X[indices]처럼 사용. 당연히 거리는 일종의 유사도로 생각할 수 있으므로 가장 가까운 두 개의 샘플은 새로운 꽃 샘플과 가장 가까운 두 개의 꽃.

In [9]:
# metric 매개변수를 사용해 거리 측정 방법 지정.
# 유클리드 거리 기반으로 가장 가까운 두 개의 최근접 이웃을 찾음.

nearestneighbors_euclidean = NearestNeighbors(n_neighbors = 2, metric='euclidean').fit(X_standardized)

In [12]:
# 거리를 확인. distance 변수는 가장 가까운 두 개의 이웃까지 실제 거릿값.
distances

array([[0.49140089, 0.74294782]])

kneighbors_grah 메서드를 사용해 샘플의 최근접 이웃을 나타내는 행렬 생성.


In [14]:
# 유클리드 거리를 기반으로 각 샘플에 대해(자기 자신을 포함한)
# 세 개의 최근접 이웃을 찾음.

nearestneighbors_euclidean = NearestNeighbors(n_neighbors= 3, metric='euclidean').fit(X_standardized)

# 각 샘플의 (자기 자신을 포함한) 3개의 최근접 이웃을 나타내는 리스트의 리스트
nearest_neighbors_with_self = nearestneighbors_euclidean.kneighbors_graph(X_standardized).toarray()

In [15]:
nearest_neighbors_with_self

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [16]:
nearest_neighbors_with_self2 = nearestneighbors_euclidean.kneighbors_graph(X_standardized)

In [17]:
nearest_neighbors_with_self2 

<150x150 sparse matrix of type '<class 'numpy.float64'>'
	with 450 stored elements in Compressed Sparse Row format>

In [18]:
# 최근접 이웃 중에서 1로 표시된 자기 자신을 제외시킴.
for i, x in enumerate(nearest_neighbors_with_self):
    x[i]=0
    
# 첫 번째 샘플에 대한 두 개의 최근접 이웃을 확인.
nearest_neighbors_with_self[0]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

최근접 이웃을 찾거나 거리 기반의 학습 알고리즘을 사용할 때 특성을 같은 스케일을 갖도록 변환하는 것이 중요. 이런 이유는 거리 측정 방법이 모든 특성을 같은  스케일로 다루기 때문. 만약 한 특성이 수 백만 달러 값이고 다른 특성이 퍼센트 값이면 계산된 거리는 전자에 편향. -StandardScaler 표준화로 해결


In [19]:
'''
kneighbors 메서드에서 n_neighbors 매개변수를 다르게 지정. return_distance를 False로 지정하면 최근접 이웃의 인덱스만 반환.

new_observation = [1,1,1,1]
'''

# 이 샘플과 가장 가까운 이웃의 다섯 개의 인덱스를 찾음.
indices= nearest_neighbors.kneighbors([new_observation], n_neighbors= 5, return_distance = False)
indices

array([[124, 110, 148, 136, 144]], dtype=int64)

In [20]:
X[indices]

array([[[6.7, 3.3, 5.7, 2.1],
        [6.5, 3.2, 5.1, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.7, 3.3, 5.7, 2.5]]])

radius_neighbors 메서드는 주어진 반경 내의 이웃을 모두 찾아줌. 반경은 Nearest Neighbors 클래스의 radius에 지정 가능. 이 매개변수의 기본값은 1.0 또한 radius_neighbors 메서드에서도 radius 값을 설정 가능.



In [24]:
# 반경 0.5안에 있는 모든 샘플의 인덱스를 찾음

indices = nearest_neighbors.radius_neighbors([new_observation],radius=0.5, return_distance=False)

# 반경 내의 이웃을 확인

print(indices)
print()

print(X_standardized[indices[0]])

[array([124], dtype=int64)]

[[1.03800476 0.55861082 1.10378283 1.18556721]]


kneighbors_graph 메서드와 마찬가지로 radius_neighbors_graph를 사용해 반경 내의 이웃을 나타내는 행렬 생성 가능. 이 메서드도 희소 행렬을 반환하기 때문에 
toarray 메서드를 사용해 밀집 배열로 바꿈!

In [27]:
# 반경 내의 이웃을 나타내는 리스트의 리스트
nearest_neighbors_with_self = nearest_neighbors.radius_neighbors_graph([new_observation], radius=0.5).toarray()

In [29]:

# 첫 번째 샘플에 대한 반경 내의 이웃을 확인
nearest_neighbors_with_self[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
nearest_neighbors_with_self

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]])

In [31]:
nearest_neighbors_with_self.shape

(1, 150)

In [32]:
nearest_neighbors_with_self2 = nearest_neighbors.radius_neighbors_graph([new_observation], radius=0.5)

In [35]:
nearest_neighbors_with_self2

<1x150 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [36]:
print(nearest_neighbors_with_self2)

  (0, 124)	1.0


In [37]:
print(nearest_neighbors_with_self)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]]


# 15.2 K-최근접 이웃 분류기 만들기

클래스를 모르는 샘플이 주어졌을 때 이웃한 샘플의 클래스를 기반으로 이 샘플의 클래스를 예측 -데이터셋이 아주 크지 않으면 KNeighborsClassifier를 사용

In [40]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import datasets

iris = datasets.load_iris()
X= iris.data
Y = iris.target

# 표준화 객체를 만듬
standardizer = StandardScaler()

X_standardized = standardizer.fit_transform(X)

# 5개의 이웃을 사용한 KNN 분류기를 훈련
knn = KNeighborsClassifier(n_neighbors= 5 , n_jobs =-1).fit(X_standardized,Y)

# 두 개의 샘플 새엇ㅇ
new_observations = [[0.75,0.75,0.75,0.75], [1,1,1,1]]

# 두 샘플의 클래스를 예측
knn.predict(new_observations)

array([1, 2])

타깃 클래스를 모르는 샘플x가 주어지면 KNN 알고리즘은 먼저 어떤 거리 측정 방법(예를 들면 유클리드 거리)을 기반으로 가장 가까운 K개의 샘플(x의 이웃)을 찾음. 그다음 이 k개 샘플의 클래스를 기반으로 투표. 가장 많은 표를 얻은 클래스가 x의 예측 클래스가 됌.

In [41]:
# 사이킷런에서는 predict_proba 메서드를 사용해 이 확률을 출력.
# 각 샘플이 세 클래스에 속할 확률을 확인
knn.predict_proba(new_observations)

# [0,1,2] 로 첫번 째는 1일 확률이 0.6으로 1 두 번째는 2일 확률이 100%이므로 2로 예측.

array([[0. , 0.6, 0.4],
       [0. , 0. , 1. ]])

In [43]:
knn.predict(new_observations) #  예측 확인

array([1, 2])

KNeighborsClassifier에는 중요한 매개변수가 많음. 

첫째, metric은 사용할 거리 측정 방법을 지정. 

둘째, n_jobs는 얼마나 ㅁ낳은 컴퓨터 코어를 사용할지 결정.

셋째, algorithm 매개변수는 가장 가까운 이웃을 계산하기 위한 방법을 지정

넷째 weights를 distance로 지정하면 멀리 떨어진 샘플보다 가까운 이웃의 투표에 가중치가 더 부여.

 회귀 문제에는 KNeighborsRegressor 클래스 사용 사용법은 KNeighborsClassifier와 매우 비슷 보스턴 데이터셋을 사용한 최근접 회귀 모델 훈련
 

In [50]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.datasets import load_boston

boston = load_boston()
X= boston.data
Y= boston.target

knnRegre = KNeighborsRegressor(n_neighbors= 10)

model = knnRegre.fit(X,Y)

# 첫 번째 샘플의 타깃값을 예측하고 1000을 곱함
model.predict(X[0:1])[0]*1000

23089.999999999996

In [60]:
model.predict(X[0:1])[0]*1000

23089.999999999996

In [67]:
Y[0]*1000

24000.0

In [ ]:
'''
KNeighborsClassfier 와 KNeighborsRegressor는 모두 NearestNeighbors 클래스를 상속하기 때문에 kneighbors 메서드를 사용해 최근접 이웃 확인 가능.

'''

In [66]:
import numpy as np
indices = model.kneighbors(X[0:1],return_distance = False)
np.mean(Y[indices])*1000

23089.999999999996

In [70]:
import numpy as np
indices = model.kneighbors(X[0:1],return_distance = True)
np.mean(Y[indices])*1000

IndexError: arrays used as indices must be of integer (or boolean) type

In [71]:
import numpy as np
distance,indices = model.kneighbors(X[0:1],return_distance = True)
np.mean(Y[indices])*1000

23089.999999999996

# 15.3 최선의 이웃 개수 결정

K-최근접 이웃 분류기에서 최선의 K값을 찾음 - GridSearchCV와 같은 모델 선택 기법사용

In [74]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline, FeatureUnion

In [75]:
iris = datasets.load_iris()

X= iris.data
Y = iris.target

scaler = StandardScaler()

X_std = scaler.fit_transform(X)

knn = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)

# 파이프라인 생성

pipe = Pipeline([("standardizer",scaler),('knn',knn)])

# 탐색 영역의 후보를 만듬.
search_space = [{'knn__n_neighbors': [1,2,3,4,5,6,7,8,9,10]}]

# 그리드 서치를 마늗ㅁ
classifier = GridSearchCV(pipe, search_space, cv=5 , verbose=0).fit(X,Y)

k 값의 크기는 KNN 분류기에 큰 영향을 미침. 편향과 분산 사이에 균형점을 찾아야 하는 머신런이에서 k 값만큼 명확한 경우가 많지 않음. n이 샘플의 개수 일때 k== n이면 편향이 높고 분산이 낮음. k==1 이면 편향이 낮고 분산이 높음. 이 편향-분산 생쇄 오프의 균형을 맞추는 k값을 찾으면 최선의 모델을 만들 수 있음 해결에서 KNN 분류기에 각기 다른 k 값으로 5-폴드 교차검증을 수행하는 GridSearchCV를 사용. 그리드 서치가 완료되면 최선의 모델을 만드는 K를 확인.

In [76]:
classifier.best_estimator_.get_params()["knn__n_neighbors"]

6

# 15.4 반지름 기반의 최근접 이웃 분류기 만들기

클래스를 모르는 샘플이 주어졌을 때 일정 거리 내의 모든 샘플의 클래스를 기반으로 이 샘플의 클래스를 예측 - RadiusNeighborsClassifier 사용

In [78]:
from sklearn.neighbors import RadiusNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import datasets

iris = datasets.load_iris()

X= iris.data
Y = iris.target

scaler = StandardScaler()

X_std = scaler.fit_transform(X)

In [79]:
# 반지름 이웃 분류기를 훈련

rnn= RadiusNeighborsClassifier(radius = .5, n_jobs = -1).fit(X_std,Y)

# 샘플 생성
new_observations = [[1,1,1,1]]

rnn.predict(new_observations)

array([2])

KNN 분류에서 샘플의 클래스는 k개 이웃의 클래스로부터 예측. 반지름 기반(RNN) 분류기는 이보다는 덜 사용되는 분류 방법. 여기서 샘플의 클래스가 주어진 반지름 r 이내에 있는 모든 샘플의 클래스로부터 예측. 

RadiusNeighborsClassifer는 radius 매개변수로 고정 영역의 반지름을 지정하여 이웃 샘플을 결정. radius를 어떤 값을 지정할 확실한 근거가 있지 않다면 다른 하이퍼파라미터처럼 모델 선택 과정으로 튜닝!

두번째로 유용한 매개변수는 outlier_label. 반지름 내에 다른 샘플이 하나도 없는 샘플에 부여할 레이블을 지정. 이 기능을 outlier를 구별하는 데 종종 유용하게 사용. 

outlier_label 매개변수의 기본값은 None으로 이웃한 샘플을 찾지 못할 경우 예외 발생. 예외를 일으키는 대신 이상치로 표시하려면 일반적으로 클래스 레이블로 사용하지 않는 -1 지정

In [80]:
# 반지름 이웃 분류기를 훈련.

rnn = RadiusNeighborsClassifier(radius=.5, outlier_label =1, n_jobs=-1 ).fit(X,Y)
rnn.predict([[100,100,100,100]])



array([1])